#!/usr/bin/env python3
"""Generate test vectors for the Ajtai decider-opening Noir circuit.

Emits:
  - src/roots.nr: the 13 per-level step roots (forward + inverse) for the
    negacyclic NTT over q0 at N=8192, plus psi/n_inv (tiny).
  - Prover.toml: A (kappa x m, NTT form), w (m, coefficient form), and
    cm = A * w (NTT form) as prover inputs.
"""
import sys

Q0 = 2305843009211596801  # ProdParams channel 0 (61-bit)
N = 16384
KAPPA = 4
B = 1 << 15

def find_psi(q, n):
    def factor(n_):
        f = {}
        d = 2
        while d * d <= n_:
            while n_ % d == 0:
                f[d] = f.get(d, 0) + 1
                n_ //= d
            d += 1 if d == 2 else 2
        if n_ > 1:
            f[n_] = f.get(n_, 0) + 1
        return f

    fac = list(factor(q - 1).keys())
    g = 2
    while True:
        if all(pow(g, (q - 1) // p, q) != 1 for p in fac):
            return pow(g, (q - 1) // (2 * n), q)
        g += 1

def ntt(values, psi, q, n):
    a = list(values)
    p = 1
    for i in range(n):
        a[i] = a[i] * p % q
        p = p * psi % q
    j = 0
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            a[i], a[j] = a[j], a[i]
    length = 2
    while length <= n:
        step = pow(psi * psi % q, n // length, q)
        for start in range(0, n, length):
            f = 1
            for off in range(length // 2):
                left = a[start + off]
                right = a[start + off + length // 2] * f % q
                a[start + off] = (left + right) % q
                a[start + off + length // 2] = (left - right) % q
                f = f * step % q
        length <<= 1
    return a

def bit_reverse(values, n):
    """Apply the bit-reverse permutation (used to permute A and cm
    off-circuit so the circuit can skip its own in-circuit permutation:
    the opening check is pointwise and permutation-invariant)."""
    out = list(values)
    j = 0
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            out[i], out[j] = out[j], out[i]
    return out

def main():
    out_dir = sys.argv[1]
    m = int(sys.argv[2]) if len(sys.argv) > 2 else 3
    n = int(sys.argv[3]) if len(sys.argv) > 3 else N
    permute = int(sys.argv[4]) if len(sys.argv) > 4 else 1
    psi = find_psi(Q0, n)
    assert pow(psi, 2 * n, Q0) == 1 and pow(psi, n, Q0) == Q0 - 1
    omega = psi * psi % Q0
    omega_inv = pow(omega, Q0 - 2, Q0)
    psi_inv = pow(psi, Q0 - 2, Q0)
    n_inv = pow(n, Q0 - 2, Q0)
    levels = n.bit_length() - 1

    fwd_steps = []
    inv_steps = []
    length = 2
    while length <= n:
        fwd_steps.append(pow(omega, n // length, Q0))
        inv_steps.append(pow(omega_inv, n // length, Q0))
        length <<= 1
    # The circuit uses the decimation-in-frequency butterfly (natural input,
    # bit-reversed output — verified numerically), so its per-level steps
    # run from length = n down to 2.
    dif_steps = list(reversed(fwd_steps))

    seed = 12345
    def rnd():
        nonlocal seed
        seed = (seed * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        return seed % Q0

    A = [[[rnd() for _ in range(n)] for _ in range(m)] for _ in range(KAPPA)]
    w = [[(k * 7 + j * 3 + 1) % 9 - 4 for k in range(n)] for j in range(m)]
    w_ntt = [ntt(wj, psi, Q0, n) for wj in w]
    cm = [[sum(A[i][j][k] * w_ntt[j][k] for j in range(m)) % Q0 for k in range(n)]
          for i in range(KAPPA)]

    # Permute A and cm off-circuit (only needed by the in-circuit-permutation
    # NTT design; the Schwartz–Zippel design uses natural NTT order).
    if permute:
        A = [[bit_reverse(row, n) for row in Ai] for Ai in A]
        cm = [bit_reverse(row, n) for row in cm]

    challenge = rnd()
    with open(f"{out_dir}/src/roots.nr", "w") as f:
        f.write("// Auto-generated by gen_vectors.py - do not edit.\n")
        f.write(f"pub global Q0: Field = {Q0};\n")
        f.write(f"pub global PSI: Field = {psi};\n")
        f.write(f"pub global OMEGA: Field = {omega};\n")
        f.write(f"pub global PSI_INV: Field = {psi_inv};\n")
        f.write(f"pub global N_INV: Field = {n_inv};\n")
        f.write(f"pub global LEVELS: u32 = {levels};\n")
        f.write(f"pub global DIF_STEPS: [Field; {levels}] = {dif_steps};\n")
        f.write(f"pub global FWD_STEPS: [Field; {levels}] = {fwd_steps};\n")
        f.write(f"pub global INV_STEPS: [Field; {levels}] = {inv_steps};\n")
        # a fixed random-looking challenge for the SZ design's r input
        f.write(f"pub global R_CHALLENGE: Field = {challenge};\n")

    def fmt(v):
        return "[" + ", ".join(str(x) for x in v) + "]"

    def fmt_nested(m_):
        return "[" + ", ".join(fmt(row) for row in m_) + "]"

    with open(f"{out_dir}/Prover.toml", "w") as f:
        f.write(f"w = {fmt_nested([[x % Q0 for x in wj] for wj in w])}\n")
        f.write(f"a_in = {fmt_nested([A[i][j] for i in range(KAPPA) for j in range(m)])}\n")
        f.write(f"cm = {fmt_nested(cm)}\n")
        f.write(f"r = {challenge}\n")
    print(f"wrote {out_dir}/src/roots.nr and {out_dir}/Prover.toml (m={m}, N={n})")

if __name__ == "__main__":
    main()
