#!/usr/bin/env python3
"""Generate test vectors for the C7 final-decryption circuit.

Models T=2 reconstruction parties over the 3 RNS channels (58-bit) plus the
176-bit P track: computes Lagrange coefficients, per-channel interpolated
residues, Garner digits, quotient witnesses, and the decode (m, e).
"""
import sys

QS = [288230376128643073, 288230376090894337, 288230376019591169]
P = 95780971232337531050942682516136025943519008502317057
T_PLAIN = 1 << 20
Q = QS[0] * QS[1] * QS[2]
DELTA = (Q - 1) // T_PLAIN

def inv(a, m):
    return pow(a, m - 2, m)

def main():
    out_dir = sys.argv[1]
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 1024

    # two reconstruction parties at x = 1, 2: lambdas 2 and -1
    points = [1, 2]
    lambdas = []
    for i, x in enumerate(points):
        lam = 1
        for j, y in enumerate(points):
            if i != j:
                lam = lam * y % QS[0] * inv((y - x) % QS[0], QS[0]) % QS[0]
        lambdas.append(lam)

    # random source: a valid plaintext + small noise, then consistent shares
    seed = 4242
    def rnd(q):
        nonlocal seed
        seed = (seed * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        return seed % q

    # u = Delta * m + e with small e (a valid pre-decode value)
    mv = [(rnd(1000) + 7) % T_PLAIN for _ in range(n)]
    ev = [rnd(1 << 40) for _ in range(n)]
    uv = [DELTA * mv[k] + ev[k] for k in range(n)]
    u_l = [[u % q for u in uv] for q in QS]

    # decryption shares consistent with the interpolation u_l = 2*d_1 - d_2:
    # pick d_2 random, solve d_1 = (u_l + d_2) * inv(2) mod q_l
    d = []
    for l, q in enumerate(QS):
        d2 = [rnd(q) for _ in range(n)]
        d1 = [(u_l[l][k] + d2[k]) * inv(2, q) % q for k in range(n)]
        d.append([d1, d2])

    # CRT (Garner) + decode per coefficient
    r0v, t1v, t2v, s0v, s1v, s2v = [], [], [], [], [], []
    for k in range(n):
        r0 = u_l[0][k]
        t1 = (u_l[1][k] - r0 % QS[1]) % QS[1] * inv(QS[0] % QS[1], QS[1]) % QS[1]
        x01 = r0 + QS[0] * t1
        t2 = (u_l[2][k] - x01 % QS[2]) % QS[2] * inv((QS[0] * QS[1]) % QS[2], QS[2]) % QS[2]
        u = x01 + QS[0] * QS[1] * t2
        assert u == uv[k]
        r0v.append(r0); t1v.append(t1); t2v.append(t2)
        s0v.append((u - u_l[0][k]) // QS[0])
        s1v.append((u - u_l[1][k]) // QS[1])
        s2v.append((u - u_l[2][k]) // QS[2])

    with open(f"{out_dir}/src/roots.nr", "w") as f:
        f.write("// Auto-generated by gen_c7_vectors.py - do not edit.\n")
        f.write(f"pub global Q_0: u64 = {QS[0]};\n")
        f.write(f"pub global Q_1: u64 = {QS[1]};\n")
        f.write(f"pub global Q_2: u64 = {QS[2]};\n")
        f.write(f"pub global DELTA: Field = {DELTA};\n")
        f.write(f"pub global DELTA_HALF: Field = {DELTA // 2};\n")
        f.write(f"pub global T_PLAIN: u64 = {T_PLAIN};\n")
        f.write(f"pub global LAMBDAS_0: [Field; 2] = {lambdas};\n")
        # lambdas mod the other two primes
        for l in (1, 2):
            lam_l = []
            for i, x in enumerate(points):
                lam = 1
                for j, y in enumerate(points):
                    if i != j:
                        lam = lam * y % QS[l] * inv((y - x) % QS[l], QS[l]) % QS[l]
                lam_l.append(lam)
            f.write(f"pub global LAMBDAS_{l}: [Field; 2] = {lam_l};\n")

    def fmt(v):
        return "[" + ", ".join(f'"{x}"' for x in v) + "]"

    with open(f"{out_dir}/Prover.toml", "w") as f:
        for l in range(3):
            for i in range(2):
                f.write(f"d_{l}_{i+1} = {fmt(d[l][i])}\n")
        f.write(f"u_0 = {fmt(u_l[0])}\n")
        f.write(f"u_1 = {fmt(u_l[1])}\n")
        f.write(f"u_2 = {fmt(u_l[2])}\n")
        f.write(f"r0 = {fmt(r0v)}\n")
        f.write(f"t1 = {fmt(t1v)}\n")
        f.write(f"t2 = {fmt(t2v)}\n")
        f.write(f"s0 = {fmt(s0v)}\n")
        f.write(f"s1 = {fmt(s1v)}\n")
        f.write(f"s2 = {fmt(s2v)}\n")
        f.write(f"u = {fmt(uv)}\n")
        f.write(f"m = {fmt(mv)}\n")
        f.write(f"e = {fmt(ev)}\n")
    print(f"wrote {out_dir}/src/roots.nr and {out_dir}/Prover.toml (N={n})")

if __name__ == "__main__":
    main()
