#!/usr/bin/env python3
"""Generate test vectors for the C5 aggregation circuit (3 RNS tracks).

Per track t with modulus q_t (58-bit): witness w = (sk, e, e_sm) short,
Ajtai matrix A_t, commitments cm_t = A_t * NTT(w), the CRS element a_t
(NTT form), and pk0_agg = -a_t * NTT(sk) + NTT(e) (mod q_t).
"""
import sys

QS = [288230376128643073, 288230376090894337, 288230376019591169]
KAPPA = 4
B = 1 << 15

def find_psi(q, n):
    def factor(n_):
        f = {}
        d = 2
        while d * d <= n_:
            while n_ % d == 0:
                f[d] = f.get(d, 0) + 1
                n_ //= d
            d += 1 if d == 2 else 2
        if n_ > 1:
            f[n_] = f.get(n_, 0) + 1
        return f

    fac = list(factor(q - 1).keys())
    g = 2
    while True:
        if all(pow(g, (q - 1) // p, q) != 1 for p in fac):
            return pow(g, (q - 1) // (2 * n), q)
        g += 1

def ntt(values, psi, q, n):
    a = list(values)
    p = 1
    for i in range(n):
        a[i] = a[i] * p % q
        p = p * psi % q
    j = 0
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            a[i], a[j] = a[j], a[i]
    length = 2
    while length <= n:
        step = pow(psi * psi % q, n // length, q)
        for start in range(0, n, length):
            f = 1
            for off in range(length // 2):
                left = a[start + off]
                right = a[start + off + length // 2] * f % q
                a[start + off] = (left + right) % q
                a[start + off + length // 2] = (left - right) % q
                f = f * step % q
        length <<= 1
    return a

def bit_reverse(values, n):
    out = list(values)
    j = 0
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            out[i], out[j] = out[j], out[i]
    return out

def main():
    out_dir = sys.argv[1]
    n = int(sys.argv[2]) if len(sys.argv) > 2 else 1024
    permute = int(sys.argv[3]) if len(sys.argv) > 3 else 1
    levels = n.bit_length() - 1

    seed = 777
    def rnd(q):
        nonlocal seed
        seed = (seed * 6364136223846793005 + 1442695040888963407) % (1 << 64)
        return seed % q

    roots_src = ["// Auto-generated by gen_c5_vectors.py - do not edit."]
    prover = []
    for t, q in enumerate(QS):
        psi = find_psi(q, n)
        assert pow(psi, 2 * n, q) == 1 and pow(psi, n, q) == q - 1
        omega = psi * psi % q
        steps = []
        length = 2
        while length <= n:
            steps.append(pow(omega, n // length, q))
            length <<= 1
        # The circuits use the DIF butterfly (length from n down to 2).
        dif_steps = list(reversed(steps))
        roots_src.append(f"pub global Q_{t}: u64 = {q};")
        roots_src.append(f"pub global PSI_{t}: Field = {psi};")
        roots_src.append(f"pub global OMEGA_{t}: Field = {omega};")
        roots_src.append(f"pub global STEPS_{t}: [Field; {levels}] = {dif_steps};")

        w = [[(k * 5 + j * 3 + t + 1) % 9 - 4 for k in range(n)] for j in range(3)]
        w_ntt = [ntt(wj, psi, q, n) for wj in w]
        A = [[[rnd(q) for _ in range(n)] for _ in range(3)] for _ in range(KAPPA)]
        cm = [[sum(A[i][j][k] * w_ntt[j][k] for j in range(3)) % q for k in range(n)]
              for i in range(KAPPA)]
        a_crs = [rnd(q) for _ in range(n)]  # coefficient form
        a_crs_ntt = ntt(a_crs, psi, q, n)
        pk0_agg = [(q - (a_crs_ntt[k] * w_ntt[0][k] % q) + w_ntt[1][k]) % q for k in range(n)]

        # Permute off-circuit only for the in-circuit-permutation design
        # (permute=1); the Schwartz–Zippel design uses natural NTT order.
        if permute:
            A = [[bit_reverse(row, n) for row in Ai] for Ai in A]
            cm = [bit_reverse(row, n) for row in cm]
            a_crs_ntt = bit_reverse(a_crs_ntt, n)
            pk0_agg = bit_reverse(pk0_agg, n)

        def fmt(v):
            return "[" + ", ".join(str(x) for x in v) + "]"

        def fmt_nested(m_):
            return "[" + ", ".join(fmt(row) for row in m_) + "]"

        prover.append(f"w_{t} = {fmt_nested([[x % q for x in wj] for wj in w])}")
        prover.append(f"a_in_{t} = {fmt_nested([A[i][j] for i in range(KAPPA) for j in range(3)])}")
        prover.append(f"cm_{t} = {fmt_nested(cm)}")
        prover.append(f"a_crs_ntt_{t} = {fmt(a_crs_ntt)}")
        prover.append(f"pk0_agg_{t} = {fmt(pk0_agg)}")

    with open(f"{out_dir}/src/roots.nr", "w") as f:
        f.write("\n".join(roots_src) + "\n")
    with open(f"{out_dir}/Prover.toml", "w") as f:
        f.write("\n".join(prover) + "\n")
    print(f"wrote {out_dir}/src/roots.nr and {out_dir}/Prover.toml (3 tracks, N={n})")

if __name__ == "__main__":
    main()
